import { compact, full } from "../lib/format";
import type { ReportSnapshot } from "../lib/snapshot";

const delta = (n: number | null) => {
  if (n === null) return <span className="delta --flat muted">—</span>;
  const r = Math.round(n);
  return <span className={`delta ${r > 0 ? "--pos" : r < 0 ? "--neg" : "--flat"}`}>{r > 0 ? "+" : ""}{r}%</span>;
};

/** Pure, print-friendly render of a report snapshot. Shared by the live
 *  Reports page and the public /r/:slug viewer so they never drift. */
export default function ReportSheet({ snap }: { snap: ReportSnapshot }) {
  const generated = new Date(snap.generatedAt).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });
  return (
    <div className="sheet">
      <header className="sheet__head">
        <span className="brandmark">
          <span className="glyph"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round"><path d="M2 12h4l2.5-7 4 15 3-9 2 3h4.5" /></svg></span>
          <b>PulseBoard</b>
        </span>
        <div style={{ textAlign: "right" }}>
          <div style={{ fontWeight: 600, fontSize: 14 }}>Performance report</div>
          <div className="muted" style={{ fontSize: 12 }}>{snap.scopeLabel} · last {snap.range} days · {generated}</div>
        </div>
      </header>

      <h4 className="sheet__h">Headline metrics</h4>
      <div className="table-wrap">
        <table className="data">
          <thead><tr><th>Metric</th><th className="num">Total</th><th className="num">Trend</th></tr></thead>
          <tbody>
            {snap.headline.map((h) => (
              <tr key={h.label}><td>{h.label}</td><td className="num tnum">{full(h.total)}</td><td className="num">{delta(h.deltaPct)}</td></tr>
            ))}
            <tr><td>Engagement rate</td><td className="num tnum">{snap.engagementRate.toFixed(1)}%</td><td className="num muted">—</td></tr>
          </tbody>
        </table>
      </div>

      <h4 className="sheet__h">By platform</h4>
      <div className="table-wrap">
        <table className="data">
          <thead><tr><th>Platform</th><th className="num">Followers</th><th className="num">Reach</th><th className="num">Views</th><th className="num">Engagements</th></tr></thead>
          <tbody>
            {snap.platforms.map((p) => (
              <tr key={p.name}>
                <td>{p.name}</td>
                <td className="num tnum">{compact(p.followers)}</td>
                <td className="num tnum">{compact(p.reach)}</td>
                <td className="num tnum">{compact(p.views)}</td>
                <td className="num tnum">{compact(p.engagements)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {snap.top.length > 0 && <>
        <h4 className="sheet__h">Top content</h4>
        <div className="table-wrap">
          <table className="data">
            <thead><tr><th>Post</th><th>Platform</th><th className="num">Views</th><th className="num">Likes</th><th className="num">Comments</th></tr></thead>
            <tbody>
              {snap.top.map((c, i) => (
                <tr key={i}>
                  <td className="cell-clamp">{c.title}</td>
                  <td>{c.platform}</td>
                  <td className="num tnum">{compact(c.views)}</td>
                  <td className="num tnum">{compact(c.likes)}</td>
                  <td className="num tnum">{compact(c.comments)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </>}

      <div className="sheet__cols">
        {snap.windows.length > 0 && <div>
          <h4 className="sheet__h">Best times to post</h4>
          <ul className="sheet__list">{snap.windows.map((w, i) => <li key={i}>{w}</li>)}</ul>
        </div>}
        <div>
          <h4 className="sheet__h">Notable moves</h4>
          {snap.alerts.length === 0
            ? <p className="muted" style={{ fontSize: 12.5 }}>Nothing unusual this period.</p>
            : <ul className="sheet__list">{snap.alerts.map((a, i) => <li key={i}>{a.label} {a.kind === "drop" ? "dropped" : "spiked"} {Math.abs(Math.round(a.deltaPct))}% on {a.date}</li>)}</ul>}
        </div>
      </div>

      <footer className="sheet__foot">Generated by PulseBoard from live platform data. Figures cover the selected window and scope.</footer>
    </div>
  );
}
